Check on existence of unpackArchive path
carvel-dev/vendir pull request #191
Opened 2022-10-11 11:08 UTC by kumaritanushree

Added check on existence of `unpackArchive` path and throw detailed error if path does not found.
Fixes  #184

2022-10-11 14:42 UTC, joaopapereira requested changes
I added a comment about the error message.
Also, do you think adding some tests around this behavior is possible?

2022-10-11 14:42 UTC, joaopapereira commented on pkg/vendir/fetch/githubrelease/sync.go
> +			return lockConf, err
I think we should be a little bit more explicit on the error message. If it is PathNotFound we should let people know that the file they want to unpack is not part of the github release

2022-10-13 07:53 UTC, kumaritanushree commented on pkg/vendir/fetch/githubrelease/sync.go
> +			return lockConf, err
Updated error with more information and added e2e test as well.

2022-10-13 15:06 UTC, joaopapereira requested changes
The implementation looks good, please just ensure you are using a temp directory to store the results of the test

2022-10-13 15:06 UTC, joaopapereira commented on test/e2e/github_release_test.go
> +		_, err := vendir.RunWithOpts([]string{"sync", "-f", "-"}, RunOpts{StdinReader: strings.NewReader(yaml), AllowError: true})
I think we should use a temporary directory to run these tests on. If not we will be polluting the folder where the test file is present

2022-10-17 15:29 UTC, joaopapereira requested changes
A couple of comments.

When you use the assert package in testify even if the assertion fails the test continues and in cases where we want to check for error we should always use require because if the assertion fails the test will stop. Usually, there is no good reason to continue a test when we are checking for the existence or absence of an error and that assertion fails.

2022-10-17 15:29 UTC, joaopapereira commented on test/e2e/github_release_test.go
> +	}
```suggestion
	require.NoError(t, err)
```

This change is just to keep the pattern we are using consistent

2022-10-17 15:29 UTC, joaopapereira commented on test/e2e/github_release_test.go
> +	"github.com/stretchr/testify/assert"
```suggestion
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
```

2022-10-17 15:29 UTC, joaopapereira commented on test/e2e/github_release_test.go
> +		assert.Error(t, err, "Expected to err while syncing with github release")
```suggestion
		require.Error(t, err, "Expected to err while syncing with github release")
```

2022-10-17 15:29 UTC, joaopapereira commented on test/e2e/github_release_test.go
> +		assert.NoError(t, err)
```suggestion
		require.NoError(t, err)
```

2022-10-17 15:54 UTC, joaopapereira approved these changes
LGTM

2022-10-17 17:15 UTC, cppforlife approved these changes

2022-10-17 17:15 UTC, merged