Introduce inclusive naming check and update existing language
carvel-dev/vendir pull request #194
Opened 2022-11-16 21:19 UTC by aaronshurley

We are following the Inclusive Naming Initiative's guidance as that is what the CNCF supports.

2022-11-16 21:19 UTC, aaronshurley commented
created as a draft until https://github.com/vmware-tanzu/carvel/pull/595 lands

2022-11-21 16:30 UTC, joaopapereira commented on pkg/vendir/fetch/image/imgpkg_test.go
> +type sampleCache struct {
After some soul searching this in fact looks much more like a fake [test double](https://en.wikipedia.org/wiki/Test_double) than really a dummy object test double.
```suggestion
type fakeCache struct {
```

2022-11-21 16:30 UTC, joaopapereira requested changes
I made some comments. Do you mind doing the proposed change?

2022-11-21 17:02 UTC, aaronshurley commented
> I made some comments. Do you mind doing the proposed change?

Done. Re-submitted the PR.

2022-11-21 20:01 UTC, joaopapereira approved these changes
LGTM

2022-11-21 20:02 UTC, merged