Make directory permissions configurable
carvel-dev/vendir pull request #199
Opened 2022-12-02 07:19 UTC by hoegaarden

- Inner directories inherit permissions from the outer directory
- the permissions on the directories is changed late, so that pulling in content is not blocked

/xref: https://github.com/vmware-tanzu/carvel-vendir/issues/186

2022-12-05 23:51 UTC, cppforlife commented
cc @joaopapereira you previously had some thoughts on permissions. any objections to this PR?

2022-12-06 16:02 UTC, joaopapereira requested changes
Hey, thanks for putting together this PR.

The PR implementation looks good, I added a couple of comments mainly on the test side of the world.
Also when you finish this do you mind creating a PR in https://github.com/vmware-tanzu/carvel to update the documentation with the new permission field? The website is organized by version and your changes should be inside [this directory](https://github.com/vmware-tanzu/carvel/tree/develop/site/content/vendir/docs/develop)

2022-12-06 16:02 UTC, joaopapereira commented on test/e2e/directory_permissions_test.go
> +	"gopkg.in/yaml.v2"
We are using this library inside the code, maybe it makes sense to keep it consistent. I just realized that the gopkg one is used in a different tests, I will create a PR to fix that as well
```suggestion
	"sigs.k8s.io/yaml"
```

2022-12-06 16:02 UTC, joaopapereira commented on test/e2e/directory_permissions_test.go
> +	assert.NoError(t, err, "creating vendir.yml")
I think we should use require in this place as well as in other parts. The main difference between `require` and `assert` is that assert allows the these to continue, but in situations like this we should not continue with the execution of the test. (I did not highlight all the places where this change can be done)
```suggestion
	require.NoError(t, err, "creating vendir.yml")
```

2022-12-06 18:33 UTC, joaopapereira approved these changes
LGTM

2022-12-12 15:29 UTC, cppforlife reviewed
lets rename field name to be plural: permission => permissions

2022-12-12 18:02 UTC, merged