Fix tar.gz support
carvel-dev/vendir pull request #280
Opened 2023-08-08 15:55 UTC by reegnz

Fixes #285

2023-08-10 10:13 UTC, reegnz commented
I haven't tried with other tar.gz files, but it definitely fixed the issue for this particular one. Also the fix was inspired by this code in the go codebase: https://cs.opensource.google/go/x/build/+/2c66d68b:internal/untar/untar.go;l=34-139, particularly line 132 and 133.

2023-08-15 19:03 UTC, neil-hickey commented
hey @reegnz , so this does appear to work on the surface. I think to really validate we are going to want some more e2e tests that cover each use-case. Is this something you would be able to contribute?

2023-08-17 17:17 UTC, reegnz commented
@neil-hickey If you can point me to what exactly you'd like to see I can give it a go.

2023-09-20 15:47 UTC, joaopapereira commented
I think we need something similar to https://github.com/carvel-dev/vendir/blob/develop/test/e2e/github_release_test.go but for HTTP workflow. We might need to standup a simple HTTP server and serve a tar.gz file from it to test it out.

2023-09-20 17:01 UTC, reegnz commented
I think I'll just fetch a tar.gz from github (from this repo), that's one of those tar.gz-s what's causing the issue anyway, and that's the most life-like test.

2023-09-20 17:21 UTC, reegnz commented
Pushed the e2e test (already had this in the making today, before the local http server idea).

2023-09-20 20:08 UTC, joaopapereira requested changes
I left a comment. The linter is also failing do you mind giving it a check?

2023-09-20 20:08 UTC, joaopapereira commented on test/e2e/http_tar_test.go
> +	// defer os.RemoveAll(dstPath)
```suggestion
	defer os.RemoveAll(dstPath)
```

2023-09-21 15:22 UTC, reegnz commented
@joaopapereira fixed.

2023-09-21 18:43 UTC, joaopapereira commented
@reegnz you need to sign your commits 😄

2023-09-27 09:31 UTC, reegnz commented
@joaopapereira rebased, added signoff to commits.

2023-09-27 14:25 UTC, joaopapereira approved these changes
LGTM

2023-09-28 10:08 UTC, kumaritanushree commented
LGTM

2023-09-28 19:33 UTC, merged