Stricter caching for imgpkg bundles
carvel-dev/vendir pull request #401
Opened 2024-10-09 09:33 UTC by 100mik

Use a fully-qualified reference as key for a cache rather than the digest.

Resolves #399 and eventually carvel-dev/kapp-controller#1603

2024-10-09 09:43 UTC, 100mik commented
Confirmed that we will still only be caching artifacts with digest references as `imgpkg` code decides wether or not it a bundle is cacheable, and that remains unchanged.

2024-10-09 10:12 UTC, praveenrewar reviewed
It would be good to have a test added for this.

2024-10-09 16:20 UTC, joaopapereira requested changes
THe change looks good, but I agree with @praveenrewar we should have a test to ensure the behavior is what we expect

2024-12-12 17:27 UTC, joaopapereira commented
@100mik any update on this?

2025-04-07 14:50 UTC, joaopapereira commented
@100mik do you think you can add some tests to ensure that we will not have regressions in the future?

2026-09-08 11:15 UTC, closed without merging

2026-09-08 11:15 UTC, himsngh commented
Fix is merged via https://github.com/carvel-dev/vendir/pull/465